name: Skip YAML Files on Pull and Push Requests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'